Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1MVC.Controllers
{
    public class ApplicationTypeController : Controller
    {
        private readonly Data.ApplicationDBContext _db;

        public ApplicationTypeController(Data.ApplicationDBContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Models.ApplicationType> appType = _db.ApplicationTypes;
            return View(appType);
        }

        //GET - Create

        public IActionResult Create()
        {
            return View();
        }

        //POST - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Models.ApplicationType obj)
        {
            if(ModelState.IsValid)
            {
                _db.ApplicationTypes.Add(obj);
                _db.SaveChanges();
                return Redirect("Index");
            }
            return View(obj);
        }


        //GET - EDIT
        public IActionResult Edit(int? _id) // "int?" is nullable
        {
            if(_id == null || _id == 0)
            {
                return NotFound();
            }
            Models.ApplicationType obj = _db.ApplicationTypes.Find(_id);
           if(obj == null )
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST - EDIT
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(Models.ApplicationType obj)
        {
            if(ModelState.IsValid)
            {
                _db.ApplicationTypes.Update(obj);
                _db.SaveChanges();
                return Redirect("Index");
            }
            return View(obj);
        }


        //GET - Delete

        public IActionResult Delete(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            Models.ApplicationType obj = _db.ApplicationTypes.Find(id);
            if(obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }


        //post - Delete
        
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult DeletePost(int? id)
        {
            Models.ApplicationType appType = _db.ApplicationTypes.Find(id);
            if(appType == null)
            {
                return NotFound();
            }
            _db.ApplicationTypes.Remove(appType);
            _db.SaveChanges();
            return Redirect("Index");
        }

    }
}

Controllers/CartsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1MVC.Utility;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace WebApplication1MVC.Controllers
{
    [Authorize]//specifies that authorization is required.
    public class CartsController : Controller
    {
        private readonly Data.ApplicationDBContext _db;

        [BindProperty]
        public Models.ViewModels.productUserVM  productUserVM {get; set; }

        public CartsController(Data.ApplicationDBContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Models.shoppingCart> shoppingCartList = new List<Models.shoppingCart>();
            //retrieving the items within the session. ( cart)
            if (HttpContext.Session.Get<IEnumerable<Models.shoppingCart>>(WebConstants.sessionCart) != null
               && HttpContext.Session.Get<IEnumerable<Models.shoppingCart>>(WebConstants.sessionCart).Count() > 0)
            {
                //populating the list
                shoppingCartList = HttpContext.Session.Get<List<Models.shoppingCart>>(WebConstants.sessionCart);
            }

            List<int> productInCart = shoppingCartList.Select(i => i.productId).ToList();
            // list of all the product IDs within the card, this is used so later on we can retrieve the objects based on their ID.
            IEnumerable<Models.Product> productList = _db.Product.Where(u => productInCart.Contains(u.id));
            //will retrieve any product with the ID that matches the "productInCart" ID.

            return View(productList);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost()
        {

            return RedirectToAction(nameof(Summary));

        }

        public IActionResult Summary()
        {

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            //"claim" will only be populated if a user is logged in.
            //another method to see if someone's logged in.
            //var userID = User.FindFirstValue(ClaimTypes.Name);

            List<Models.shoppingCart> shoppingCartList = new List<Models.shoppingCart>();
            //retrieving the items within the session. ( cart)
            if (HttpContext.Session.Get<IEnumerable<Models.shoppingCart>>(WebConstants.sessionCart) != null
               && HttpContext.Session.Get<IEnumerable<Models.shoppingCart>>(WebConstants.sessionCart).Count() > 0)
            {
                //populating the list
                shoppingCartList = HttpContext.Session.Get<List<Models.shoppingCart>>(WebConstants.sessionCart);
            }

            List<int> productInCart = shoppingCartList.Select(i => i.productId).ToList();
            // list of all the product IDs within the card, this is used so later on we can retrieve the objects based on their ID.
            IEnumerable<Models.Product> productList = _db.Product.Where(u => productInCart.Contains(u.id));
            //will retrieve any product with the ID that matches the "productInCart" ID.


            //loading the session again.

            productUserVM = new Models.ViewModels.productUserVM()
            {
                ApplicationUser = _db.ApplicationUser.FirstOrDefault(u => u.Id == claim.Value)
            };

            return View(productUserVM);

        }


        public IActionResult Delete(int id)
        {
            List<Models.shoppingCart> shoppingCartList = new List<Models.shoppingCart>();
            //retrieving the items within the session. ( cart)
            if (HttpContext.Session.Get<IEnumerable<Models.shoppingCart>>(WebConstants.sessionCart) != null
               && HttpContext.Session.Get<IEnumerable<Models.shoppingCart>>(WebConstants.sessionCart).Count() > 0)
            {
                //populating the list
                shoppingCartList = HttpContext.Session.Get<List<Models.shoppingCart>>(WebConstants.sessionCart);
            }

            shoppingCartList.Remove(shoppingCartList.FirstOrDefault(u => u.productId == id));
            //finds that object and removes it from the list.

            HttpContext.Session.Set(WebConstants.sessionCart, shoppingCartList);
            //setting the session again since we removed something.
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1MVC.Data;

namespace WebApplication1MVC.Controllers
{
    public class CategoryController : Controller
    {
        //dependency injection
        private readonly ApplicationDBContext _db;

        public CategoryController(Data.ApplicationDBContext db) //constructor // pulling from the service container.
        {
            _db = db; // assigning the local db to the new one.
        }

        public IActionResult Index()
        {
            IEnumerable<Models.Category> objList = _db.Category; // gets the class from Models.Category.
            return View(objList);
        }

        //get create
        public IActionResult Create()
        {
            
            return View();
        }


        //POST - create
        [HttpPost]
        [ValidateAntiForgeryToken] //built in mechanism that check if the token is still valid and security has not been tampered.
        public IActionResult Create(Models.Category obj)
        {
            if (ModelState.IsValid) //this is server side validation. // Validation is done in the controller (CategoryController) 
            {
                _db.Category.Add(obj);
                _db.SaveChanges();
                return Redirect("Index");
            }
            return View(obj);

        }

        //GET - EDIT
        public IActionResult Edit(int? _id)
        {
            //The function paramater and the ASP-ROUTE have to be the same otherwise data will not be passed. CLAPPED.
            //Check Index for details. 
            //E.g. asp-route-_id => function paramters must be called "_id".
            if(_id==null || _id == 0)
            {
                return NotFound();
            }
            Models.Category obj = _db.Category.Find(_id); //only works with primary key. whatever is passed in will be compared against the primary keys column.
            if(obj == null)
            {
                return NotFound();
            }
                return View(obj);

        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Models.Category obj)
        {
            if (ModelState.IsValid) //this is server side validation. // Validation is done in the controller (CategoryController) 
            {
                _db.Category.Update(obj);
                _db.SaveChanges();
                return Redirect("Index");
            }
            return View(obj);

        }

        //Delete - GET
        public IActionResult Delete(int? id)
        {
            //The function paramater and the ASP-ROUTE have to be the same otherwise data will not be passed. CLAPPED.
            //Check Index for details. 
            //E.g. asp-route-_id => function paramters must be called "_id".
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Models.Category obj = _db.Category.Find(id); //only works with primary key. whatever is passed in will be compared against the primary keys column.
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        //POST - Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            Models.Category obj = _db.Category.Find(id);
            if(obj==null)
            {
                return NotFound();
            }
                _db.Category.Remove(obj);
                _db.SaveChanges();
                return Redirect("Index");

        }

    }
}

Views/Shared/_Layout.cshtml
 @using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;
@using WebApplication1MVC.Utility;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-primary" style="height:45px;" asp-area="" asp-controller="Home" asp-action="Index">Car Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" /> <!--This enables the login/registration partial view-->

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark ml-1" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="nav-link text-dark ml-1" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Types</a>
                                <a class="nav-link text-dark ml-1" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                                <!--<div class="dropdown-divider"></div> this is just a divider.
                                <a class="dropdown-item" href="#">Something else here</a>-->
                                @if (User.IsInRole(WebConstants.adminRole))
                                {
                                    <a class="nav-link text-dark ml-1" asp-area="Identity" asp-page="/Account/Register">Create admin user</a>
                                }
                            </div>
                        </li>
                        <li>
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<shoppingCart>>(WebConstants.sessionCart) != null)
                            {
                                <a asp-action="Index" asp-controller="Carts" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.Get<List<shoppingCart>>(WebConstants.sessionCart).Count;
                                    }
                                    <i class="fas fa-warehouse"></i> &nbsp; (@count)
                                </a>
                            }
                            else
                            {
                                <a asp-action="Index" asp-controller="Carts" class="nav-link">
                                    <i class="fas fa-warehouse"></i> &nbsp; (0)
                                </a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">

        <div class="container">
            &copy; 2021 - Car Management App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_individualProductCard.cshtml
@model WebApplication1MVC.Models.Product
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="col-lg-4 col-md-6 pb-4 filter @Model.category.name.Replace(' ','_')">
    <!--card-->
    <div class="card bg-white rounded shadow-sm"style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@string.Format("{0:c0}",Model.price)</span></label></div>
        </div>
    </div>
    <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WebConstants.imagePath@Model.imagePath" alt="Card image cap" />
    <div class="card-body p-1 px-3 row">
        <div class="col-6">
            <span class="badge p-2 border w-100" style="background-color:lavenderblush">@Model.category.name</span>
        </div>
        <div class="col-6 border-0">
            <span class="badge p-2 border w-100" style="background-color:aliceblue">@Model.applicationType.Name</span>
        </div>
        <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
            <p> @Model.ShortDescription</p>
        </div>
        <div class="col-12 p-1">
            <a asp-action="details" asp-route-id ="@Model.id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
        </div>
    </div>
</div>